{
 "title": "TestDockerApp",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(testdocker_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Error Rate  Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"testdocker\", status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "RPS по методам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(testdocker_total_requests[1m]))"
    }
   ]
  },
  {
   "title": "RPS по методам Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{exported_service=\"testdocker\"}[1m]))"
    }
   ]
  },
  {
   "title": "latency 0.5 по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(testdocker_request_duration_seconds_bucket[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency 0.95 по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(testdocker_request_duration_seconds_bucket[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency 0.99 по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(testdocker_request_duration_seconds_bucket[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency max по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(testdocker_request_duration_seconds_bucket[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency 0.5 по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"testdocker\"}[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency 0.95 по методам Nginx",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"testdocker\"}[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency 0.99 по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"testdocker\"}[1m]))\n) * 1000\n"
    }
   ]
  },
  {
   "title": "latency max по методам",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, \n      sum by (le, exported_endpoint) \n         (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"testdocker\"}[1m]))\n) * 1000\n"
    }
   ]
  }
 ]
}