apiVersion: v1
kind: Secret
metadata:
  name: authserver-secret
type: Opaque
data:
  DATABASE_URI: {{ printf "Host=%s;Port=%s;UserName=%s;Password=%s;Database=%s" .Values.externalPostgresql.postgresqlHost .Values.externalPostgresql.postgresqlPort .Values.externalPostgresql.postgresqlUsername .Values.externalPostgresql.postgresqlPassword .Values.externalPostgresql.postgresqlDatabase | b64enc | quote }}
 