apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userservice.fullname" . }}
  labels:
    {{- include "userservice.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "userservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "userservice.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: AuthServerUrl
              valueFrom:
                configMapKeyRef:
                  name: userservice-config
                  key: AuthServerUrl
            - name: UserDBConnection
              valueFrom:
                secretKeyRef:
                  name: userservice-secret
                  key: UserDBConnection
