apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog.fullname" . }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "catalog.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "catalog.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - name: web
              containerPort: {{ .Values.service.targetPort }}
          env:
            - name: UseCache
              valueFrom:
                configMapKeyRef:
                  name: catalog-config
                  key: UseCache
            - name: CatalogDBConnection
              valueFrom:
                secretKeyRef:
                  name: catalog-secret
                  key: CatalogDBConnection
